
steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us-west1-docker.pkg.dev/$PROJECT_ID/m-cards-repo/m-cardsv2", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-west1-docker.pkg.dev/$PROJECT_ID/m-cards-repo/m-cardsv2"]


  # deploy container image to GKE.
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke/deployment.yaml
  - --image=gcr.io/$PROJECT_ID/m-cards-repo/m-cardsv2:latest
  - --location=us-west1-c
  - --cluster=nginx-1-cluster

 # deply service.
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke/service.yaml
  - --image=gcr.io/$PROJECT_ID/m-cards-repo/m-cardsv2:latest
  - --location=us-west1-c
  - --cluster=nginx-1-cluster



# steps:
#   # Build container image.
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/m-cards-repo/m-cardsv1', '.' ]

# # Push container to Artifact.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Push
#   args: [ 'push', 'us-west1-docker.pkg.dev/$PROJECT_ID/m-cards-repo/m-cardsv1' ]

# images: ['us-west1-docker.pkg.dev/g-testv1/m-cards-repo/m-cardsv1']
options:
  logging: CLOUD_LOGGING_ONLY
