

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/g-testv1/m-cards-repo/m-cardsv1', '.' ]

images: ['us-west1-docker.pkg.dev/g-testv1/m-cards-repo/m-cardsv1']
options:
  logging: CLOUD_LOGGING_ONLY
