# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monster-cards-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-testv2
  template:
    metadata:
      labels:
        app: m-testv2
    spec:
      containers:
      - name: mcard-v2
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-west1-docker.pkg.dev/g-testv1/test-card/m-cardsv2:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"